kind: pipeline
name: Build

steps:
  - name: Run Tests
    image: node:10
    commands:
      - yarn install --offline --non-interactive --frozen-lockfile
      - yarn lint
      - yarn test

  - name: Build sources
    image: node:10
    commands:
      - yarn build

  - name: Docker image
    image: plugins/docker
    settings:
      registry: eu.gcr.io
      repo: eu.gcr.io/quiet-mechanic-140114/${DRONE_REPO_NAME}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
