pipeline:

  build:
    image: node:8
    environment:
    commands:
      - yarn install
      - yarn run build

  docker:
    image: plugins/docker
    registry: eu.gcr.io
    repo: eu.gcr.io/quiet-mechanic-140114/${DRONE_REPO_NAME}
    username: _json_key
    tag: latest
    when:
      branch: master
      event: push
